spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/gorany?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: salem
    password: salem
    
  thymeleaf:
    cache: false
    

  security:
    user:
      name: gorany
      password: 12345678


server:
  port: 8080

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  


logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.salem: debug
